/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.MusicPower.Apresentacao;


import br.edu.ifnmg.MusicPower.Entidades.ItensVenda;
import br.edu.ifnmg.MusicPower.Entidades.Produto;
import br.edu.ifnmg.MusicPower.Entidades.ProdutoRepositorio;
import br.edu.ifnmg.MusicPower.Entidades.Venda;
import br.edu.ifnmg.MusicPower.Entidades.VendaRepositorio;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import muiscpowerapresentacao.MuiscPowerApresentacao;

/**
 *
 * @author breno
 */
public class TelaOperacoesVenda extends javax.swing.JFrame {
    MuiscPowerApresentacao MPA = new MuiscPowerApresentacao();
    ProdutoRepositorio daoProduto = GerenciadorDeReferencias.getProduto();
    Produto novo;
    ArrayList<Produto> listaVenda = new ArrayList<>();
    ArrayList<Produto> busca = new ArrayList<>();
    Venda venda;
    Venda ultimaVenda;
    VendaRepositorio daoVenda = GerenciadorDeReferencias.getVenda();
    ItensVenda daoItensVenda = new ItensVenda();
    Double valorUnitario = 0.0;
    Double valorTotal = 0.0;
    int qtd = 0;
    int idProduto = 0;
    
    /**
     * Creates new form TelaVenda
     */
    public TelaOperacoesVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlCliente = new javax.swing.JPanel();
        lblCPF = new javax.swing.JLabel();
        lblClienteAtivo = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtIdFuncionario = new javax.swing.JTextField();
        lblCPF1 = new javax.swing.JLabel();
        pnlProduto = new javax.swing.JPanel();
        lblCodigoProduto = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JFormattedTextField();
        btnConsultarProduto = new javax.swing.JButton();
        lblDescricaoProduto = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblQuantidadeProduto = new javax.swing.JLabel();
        lblValorUnitarioProduto = new javax.swing.JLabel();
        txtValorUnitarioProduto = new javax.swing.JFormattedTextField();
        btnAdicionarProduto = new javax.swing.JButton();
        lblDescricaoProduto1 = new javax.swing.JLabel();
        txtDescricaoProduto = new javax.swing.JTextField();
        lblDescricaoProduto2 = new javax.swing.JLabel();
        txtLote = new javax.swing.JTextField();
        lblValorUnitarioProduto1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        btnLimparCampos = new javax.swing.JButton();
        txtQtd = new javax.swing.JFormattedTextField();
        txtQuantidade = new javax.swing.JTextField();
        lblDescricaoProduto3 = new javax.swing.JLabel();
        pnlItensVenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensVendas = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnLiquidar = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        lblOperacoesVenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Venda"));

        lblCPF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCPF.setText("*ID Funcionário:");

        lblClienteAtivo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblClienteAtivo.setForeground(new java.awt.Color(72, 131, 228));

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        txtIdFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFuncionarioActionPerformed(evt);
            }
        });

        lblCPF1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCPF1.setText("*ID Cliente:");

        javax.swing.GroupLayout pnlClienteLayout = new javax.swing.GroupLayout(pnlCliente);
        pnlCliente.setLayout(pnlClienteLayout);
        pnlClienteLayout.setHorizontalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(lblCPF1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(txtIdFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addGap(319, 319, 319))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(lblClienteAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlClienteLayout.setVerticalGroup(
            pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblClienteAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlClienteLayout.createSequentialGroup()
                        .addGroup(pnlClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 18, Short.MAX_VALUE))))
        );

        pnlProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));
        pnlProduto.setToolTipText("");

        lblCodigoProduto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCodigoProduto.setText("Código :");

        txtCodigoProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btnConsultarProduto.setText("Consultar");
        btnConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProdutoActionPerformed(evt);
            }
        });

        lblDescricaoProduto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDescricaoProduto.setText("Marca :");

        txtModelo.setEditable(false);
        txtModelo.setBackground(new java.awt.Color(136, 192, 234));
        txtModelo.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        lblQuantidadeProduto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblQuantidadeProduto.setText("Estoque:");

        lblValorUnitarioProduto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblValorUnitarioProduto.setText("Lote:");

        txtValorUnitarioProduto.setEditable(false);
        txtValorUnitarioProduto.setBackground(new java.awt.Color(136, 192, 234));
        txtValorUnitarioProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        btnAdicionarProduto.setText("Adicionar Item ");
        btnAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoActionPerformed(evt);
            }
        });

        lblDescricaoProduto1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDescricaoProduto1.setText("Modelo :");

        txtDescricaoProduto.setEditable(false);
        txtDescricaoProduto.setBackground(new java.awt.Color(136, 192, 234));
        txtDescricaoProduto.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        lblDescricaoProduto2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDescricaoProduto2.setText("Descrição :");

        txtLote.setEditable(false);
        txtLote.setBackground(new java.awt.Color(136, 192, 234));
        txtLote.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        lblValorUnitarioProduto1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblValorUnitarioProduto1.setText("Valor Unit R$:");

        txtMarca.setEditable(false);
        txtMarca.setBackground(new java.awt.Color(136, 192, 234));
        txtMarca.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        txtQtd.setEditable(false);
        txtQtd.setBackground(new java.awt.Color(136, 192, 234));
        txtQtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        lblDescricaoProduto3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDescricaoProduto3.setText("Informe a quantidade:");

        javax.swing.GroupLayout pnlProdutoLayout = new javax.swing.GroupLayout(pnlProduto);
        pnlProduto.setLayout(pnlProdutoLayout);
        pnlProdutoLayout.setHorizontalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricaoProduto1)
                    .addComponent(lblDescricaoProduto3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlProdutoLayout.createSequentialGroup()
                        .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProdutoLayout.createSequentialGroup()
                                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultarProduto)))
                        .addGap(59, 59, 59)
                        .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescricaoProduto2)
                            .addComponent(lblQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlProdutoLayout.createSequentialGroup()
                                .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValorUnitarioProduto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValorUnitarioProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescricaoProduto)
                            .addComponent(lblValorUnitarioProduto))
                        .addGap(27, 27, 27)
                        .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlProdutoLayout.createSequentialGroup()
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlProdutoLayout.setVerticalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarProduto)
                    .addComponent(lblDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescricaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricaoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricaoProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorUnitarioProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorUnitarioProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorUnitarioProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescricaoProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlItensVenda.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens Venda"));

        tblItensVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod Produto", "Descrição", "Modelo", "Marca", "QTD", "Valor Unitário", "Lote"
            }
        ));
        tblItensVendas.setFocusable(false);
        jScrollPane1.setViewportView(tblItensVendas);

        btnExcluir.setText("Remover Item");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlItensVendaLayout = new javax.swing.GroupLayout(pnlItensVenda);
        pnlItensVenda.setLayout(pnlItensVendaLayout);
        pnlItensVendaLayout.setHorizontalGroup(
            pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlItensVendaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlItensVendaLayout.setVerticalGroup(
            pnlItensVendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensVendaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        btnLiquidar.setText("Liquidar");
        btnLiquidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiquidarActionPerformed(evt);
            }
        });

        btnCancelar1.setText("Cancelar");
        btnCancelar1.setPreferredSize(null);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlItensVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLiquidar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(pnlCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlItensVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLiquidar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblOperacoesVenda.setBackground(new java.awt.Color(118, 118, 118));
        lblOperacoesVenda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblOperacoesVenda.setForeground(new java.awt.Color(1, 1, 1));
        lblOperacoesVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOperacoesVenda.setText("Operações de Vendas - Music Power");
        lblOperacoesVenda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblOperacoesVenda.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOperacoesVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblOperacoesVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Operação de Venda ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void btnConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProdutoActionPerformed

        int codProduto = Integer.parseInt(txtCodigoProduto.getText());
        if(codProduto >= 0){
            try {
              novo = daoProduto.Abrir(codProduto); 
              preencherCampos(novo);
            } catch (Exception e) {
                
            }       
        }
    }//GEN-LAST:event_btnConsultarProdutoActionPerformed

    private void btnAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoActionPerformed

            novo = new Produto();
            this.recuperacampos();
            listaVenda.add(novo);
            preencherTabela(listaVenda);
            this.limparCampos();

    }//GEN-LAST:event_btnAdicionarProdutoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int posicao = tblItensVendas.getSelectedRow();
        
        if(posicao >= 0 ){
            listaVenda.remove(posicao);
            preencherTabela(listaVenda);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLiquidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiquidarActionPerformed
        efetuarVenda();
        guardaItensVenda();
        JOptionPane.showMessageDialog(this, "Venda realizada com sucesso!!!");
    }//GEN-LAST:event_btnLiquidarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void txtIdFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFuncionarioActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoesVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoesVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoesVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOperacoesVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOperacoesVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProduto;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnConsultarProduto;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnLiquidar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblClienteAtivo;
    private javax.swing.JLabel lblCodigoProduto;
    private javax.swing.JLabel lblDescricaoProduto;
    private javax.swing.JLabel lblDescricaoProduto1;
    private javax.swing.JLabel lblDescricaoProduto2;
    private javax.swing.JLabel lblDescricaoProduto3;
    private javax.swing.JLabel lblOperacoesVenda;
    private javax.swing.JLabel lblQuantidadeProduto;
    private javax.swing.JLabel lblValorUnitarioProduto;
    private javax.swing.JLabel lblValorUnitarioProduto1;
    private javax.swing.JPanel pnlCliente;
    private javax.swing.JPanel pnlItensVenda;
    private javax.swing.JPanel pnlProduto;
    private javax.swing.JTable tblItensVendas;
    private javax.swing.JFormattedTextField txtCodigoProduto;
    private javax.swing.JTextField txtDescricaoProduto;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdFuncionario;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JFormattedTextField txtQtd;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JFormattedTextField txtValorUnitarioProduto;
    // End of variables declaration//GEN-END:variables

    
    private void preencherCampos(Produto novo) {
       
        String qtd = String.valueOf(novo.getQtd());
        String valor = String.valueOf(novo.getValor());
        
        txtDescricaoProduto.setText(novo.getDescricao());
        txtMarca.setText(novo.getMarca());
        txtModelo.setText(novo.getModelo());
        txtQtd.setText(qtd);
        txtValorUnitarioProduto.setText(valor);
        txtLote.setText(novo.getLote());
    }
    
    private void recuperacampos(){
        int id = Integer.parseInt(txtCodigoProduto.getText());
        novo.setId(id);
        novo.setDescricao(txtDescricaoProduto.getText());
        novo.setLote(txtLote.getText());
        novo.setMarca(txtMarca.getText());
        novo.setModelo(txtModelo.getText());
        int qtd =Integer.parseInt(txtQuantidade.getText());
        novo.setQtd(qtd);
        novo.setValor(Double.parseDouble(txtValorUnitarioProduto.getText()));
    }

    private void limparCampos() {
        
        txtCodigoProduto.setText("");
        txtDescricaoProduto.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtQtd.setText("");
        txtValorUnitarioProduto.setText("");
        txtLote.setText("");
        txtQuantidade.setText("");
        
    }
 
    private void preencherTabela(ArrayList<Produto> busca) {
  
        DefaultTableModel modelo = new DefaultTableModel();
       // int qtd = Integer.parseInt(txtQuantidade.getText());
        
        modelo.addColumn("Cod Produto");
        modelo.addColumn("Descrição");
        modelo.addColumn("Marca");
        modelo.addColumn("Modelo");
        modelo.addColumn("Qtd");
        modelo.addColumn("Valor");
        modelo.addColumn("Lote");
        
       for(Produto c: busca){
            Vector linha = new Vector();
            
            linha.add(c.getId());
            linha.add(c.getDescricao());
            linha.add(c.getMarca());
            linha.add(c.getModelo());
            linha.add(c.getQtd());
            linha.add(c.getValor());
            linha.add(c.getLote());
            
            modelo.addRow(linha);
            
        }
       tblItensVendas.setModel(modelo);
        
    }

    private Double calcularCompra() {
        for(Produto c: listaVenda){
            valorTotal = valorTotal + c.getQtd()*c.getValor();
        }
        return valorTotal;
    }
    
    public void efetuarVenda(){
        
        int idCliente = Integer.parseInt(txtIdCliente.getText());
        int idFuncionario = Integer.parseInt(txtIdFuncionario.getText());
        Double valorVenda = calcularCompra();
        Date date = new Date( new java.util.Date().getTime());
        venda = new Venda(0,idCliente,idFuncionario,valorVenda,date);
        try {
            ultimaVenda = MPA.criarVenda(venda);
        } catch (SQLException ex) {
            Logger.getLogger(TelaOperacoesVenda.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TelaOperacoesVenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void guardaItensVenda() {
        for(Produto c: listaVenda){
            int idVenda = ultimaVenda.getId();
            idProduto = c.getId();
            qtd = c.getQtd();
            valorUnitario = c.getValor();
            daoItensVenda = new ItensVenda(0,idVenda,idProduto,qtd,valorUnitario);
            try {
                MPA.criarItensVenda(daoItensVenda);
            } catch (SQLException ex) {
                Logger.getLogger(TelaOperacoesVenda.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TelaOperacoesVenda.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
}
